# Generated by Django 4.2 on 2023-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0012_auto_20200419_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=619151, unique=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="nationality",
            field=models.CharField(
                choices=[("Indian", "Indian"), ("Others", "Others")], max_length=45
            ),
        ),
    ]
